name: Auto Update JSON from Admin
on:
  issues:
    types: [opened]

jobs:
  update-json:
    if: contains(github.event.issue.labels.*.name, 'admin-update')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Write Data to File
        run: |
          echo '${{ github.event.issue.body }}' > search/new_web.json

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic Admin Update"
          file_pattern: search/new_web.json

      - name: Close Issue
        run: gh issue close ${{ github.event.issue.number }} --comment "Successfully updated website data!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
